Import("env")

env.Append(
    CPPPATH=[
        "#/lib/asset_packs",
    ],
)

libenv = env.Clone(FW_LIB_NAME="asset_packs")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
